import type { Metadata } from 'next'

import { Montserrat } from 'next/font/google'
import './globals.css'
import { AuthProvider } from './(User)/user'



const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
  title: 'Okukla-mkt',
  description: 'Generated by create next app',
}


 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt">
      <body className={`${montserrat.className}`}>
      <AuthProvider>
      
      {children}

    </AuthProvider>
        
        
        </body>
    </html>
  );
}
